[package]
name = "juric_pp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "1.0.10"
crossterm = "0.27.0"
crossterm_cursor = "0.4.0"
whoami = "1.4.1"
